language: python
matrix:
  include:
  - os: linux
    python: '3.6'
  - os: osx
    python: '3.3'
  - os: osx
    python: '3.4'
  - os: osx
    python: '3.5'
  - os: osx
    python: '3.6'
before_install: "pip install GitPython"
install: "./.travis/install.sh"
script: "python3 setup.py test"
